import { colors } from "../../../theme/colors";
import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  bg: { flex: 1 },
  bgImage: { opacity: 0.15 },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(11,16,33,0.65)",
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: Platform.select({ ios: 80, android: 60, default: 40 }),
  },
  header: { marginBottom: 24 },
  title: {
    fontSize: 32,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: 0.2,
  },
  subtitle: {
    marginTop: 8,
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 20,
  },
  formGroup: { marginBottom: 16 },
  label: { color: "#c9d1d9", marginBottom: 6, fontSize: 14 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
  },
  inputError: { borderColor: "#ff6b6b" },
  passwordRow: { position: "relative", justifyContent: "center" },
  passwordInput: { paddingRight: 90 },
  eyeButton: {
    position: "absolute",
    right: 8,
    top: 8,
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  eyeText: { color: colors.text, fontWeight: "600" },
  forgotLink: { alignSelf: "flex-end", marginTop: 8 },
  forgotText: { color: colors.info, fontWeight: "600" },
  primaryButton: {
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
    shadowColor: colors.accent,
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 20,
    elevation: 6,
    marginTop: 8,
  },
  primaryButtonPressed: { opacity: 0.9, transform: [{ scale: 0.995 }] },
  primaryButtonDisabled: { opacity: 0.6 },
  primaryButtonText: { color: "#f8fafc", fontSize: 16, fontWeight: "700" },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 20,
  },
  divider: { flex: 1, height: 1, backgroundColor: colors.divider },
  dividerText: { marginHorizontal: 10, color: "#64748b" },
  secondaryButton: {
    height: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: colors.outline,
  },
  secondaryButtonPressed: { opacity: 0.9 },
  secondaryButtonText: { color: "#e5e7eb", fontWeight: "700" },
  signupRow: { flexDirection: "row", justifyContent: "center", marginTop: 18 },
  signupText: { color: "#94a3b8" },
  signupLink: { color: colors.info, fontWeight: "700" },
  errorBox: {
    backgroundColor: colors.errorBg,
    borderWidth: 1,
    borderColor: colors.errorBorder,
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  errorText: { color: "#fecaca" },
  version: {
    position: "absolute",
    bottom: 20,
    alignSelf: "center",
    color: "#53627c",
    fontSize: 12,
  },
});
